"use strict";
const PACKAGES = [
  {
    id: "starter",
    category: "new",
    name: "Starter",
    price: "$500",
    summary: "For a simple business introduction.",
    features: [
      "One page with up to five sections",
      "Custom responsive design",
      "Client-supplied copy and images",
      "Simple contact or quote form",
      "Page title and search description",
      "One revision round",
    ],
  },
  {
    id: "business",
    category: "new",
    name: "Business",
    price: "$1,500",
    summary: "A complete presence for your services and work.",
    badge: "Recommended for service businesses",
    features: [
      "Up to five pages",
      "Custom responsive design",
      "Light cleanup of client-supplied copy",
      "Contact or quote form and project gallery",
      "Analytics setup and basic local search foundations",
      "Two revision rounds",
    ],
  },
  {
    id: "growth",
    category: "new",
    name: "Growth",
    price: "$2,750",
    starting: true,
    summary: "For a larger site with additional requirements.",
    features: [
      "Up to ten pages",
      "Custom responsive design and page structure",
      "Light cleanup of client-supplied copy",
      "Expanded galleries or service content",
      "Analytics and agreed inquiry tracking",
      "Three revision rounds",
    ],
    note: "Booking, CRM, and other integrations are assessed and priced individually before the quote is finalized.",
  },
  {
    id: "refresh",
    category: "existing",
    name: "Refresh",
    price: "$500",
    summary: "A focused update to one existing homepage.",
    features: [
      "Typography, colors, spacing, and layout improvements",
      "Mobile layout improvements",
      "Clearer contact buttons and calls to action",
      "Existing content reused",
      "One revision round",
    ],
    note: "Platform and access reviewed first. Additional pages, platform migration, and new functionality are excluded.",
  },
  {
    id: "redesign",
    category: "existing",
    name: "Redesign",
    price: "$1,500",
    starting: true,
    summary: "A redesign of up to five existing pages.",
    features: [
      "Responsive redesign and clearer navigation",
      "Light cleanup of supplied content",
      "Simple contact or quote form",
      "Content migration from agreed pages",
      "Analytics setup",
      "Existing URL review and agreed redirect plan",
      "Two revision rounds",
    ],
    note: "The final quote follows a review of your current site, platform, content, and integrations.",
  },
  {
    id: "rebuild",
    category: "existing",
    name: "Rebuild",
    price: "$2,750",
    starting: true,
    summary: "A new structure and build for up to ten pages.",
    features: [
      "Custom responsive design",
      "Revised navigation and page structure",
      "Content migration from agreed pages",
      "Analytics and agreed inquiry tracking",
      "An agreed URL and redirect plan",
      "Three revision rounds",
    ],
    note: "Platform migration, booking, CRM, and other integrations are assessed and priced before work begins.",
  },
];
